environments:
    - environment-name: ocne_env
      globals:
        api-server: ocne-control01:8091
      modules:
        - module: kubernetes
          name: ocne_cluster
          generate-scripts: true
          args:
            container-registry: container-registry-lhr.oracle.com/olcne
            master-nodes: 
                - ocne-control01:8090
            worker-nodes:
                - ocne-worker01:8090
            selinux: enforcing
            restrict-service-externalip: false
        - module: helm 
          name: myhelm 
          args:
            helm-kubernetes-module: ocne_cluster
